apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio
spec:
  ports:
    - name: data-port
      port: 9000
      protocol: TCP
      targetPort: 9000
      nodePort: 30123
    - name: console-port
      port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 30124
  selector:
    app: minio
  type: NodePort
