apiVersion: v1
kind: Service
metadata:
  name: dev-commonality-svc
  namespace: dev-zh
spec:
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8084
  selector:
    app: dev-zh-auth
  type: ClusterIP
