apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-nginx-pv
  namespace: dev-zh
  labels:
    pv-type: dev-nginx-nfs
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-nfs
  nfs:
    path: /data/nfs/dev-nginx
    server: 10.1.0.67
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dev-nginx-pvc
  namespace: dev-zh
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: storage-nfs
  selector:
    matchLabels:
      pv-type: dev-nginx-nfs
