apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: rabbitmq
  labels:
    name: rabbitmq-svc
spec:
  type: NodePort
  ports:
  - name: web
    port: 15672
    targetPort: 15672
    nodePort: 30672
  - name: server
    port: 5672
    targetPort: 5672
    nodePort: 30673
  selector:
    name: rabbitmq

