apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: rabbitmq
 namespace: rabbitmq
 labels:
   name: rabbitmq
spec:
 serviceName: rabbitmq
 replicas: 1
 selector:
    matchLabels:
        name: rabbitmq
 template:
   metadata:
     labels: 
      name: rabbitmq
   spec:
     nodeSelector:
       kubernetes.io/hostname: k8s-2
     containers:
     - name: rabbitmq
       #image: rabbitmq:3.6.15-management
       image: rabbitmq:3.7.8-management
       volumeMounts:
       - mountPath: /var/lib/rabbitmq
         name: rabbitmq-data
       ports:
       - containerPort: 5672
       - containerPort: 15672
     volumes:
     - name: rabbitmq-data
       persistentVolumeClaim:
         claimName: rabbitmq-pvc
