apiVersion: v1
kind: Service
metadata:
  name: dev-user-svc
  namespace: dev-zh
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30122
  selector:
    app: dev-zh-user
  type: NodePort
