apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql
data:
  mysqld.cnf: |-
    [mysqld]
    default-time_zone='+8:00'
    datadir=/var/lib/mysql
    symbolic-links=0
    max_connections=1000
    max_allowed_packet = 1000M
    character-set-server=utf8
    sql_mode ='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION'
