apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: mysql
  labels:
    app: mysql-svc
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: dbport
    nodePort: 30306
  selector:
    app: mysql
    tier: mysql

