apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis
  labels:
    app: regis-config
data:
  redis.conf: |-
    dir /data
    port 6379
    bind 0.0.0.0
    appendonly yes
    daemonize no
    protected-mode yes
    requirepass dfjx@123
    pidfile /data/redis-6379.pid
