apiVersion: v1
kind: Service
metadata:
  name: dev-auth-svc
  namespace: dev-zh
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
      nodePort: 30123
  selector:
    app: dev-zh-auth
  type: NodePort
